### ISSUE TITLE
Missing "parameter-info.json", param field blank

### ISSUE THREAD

**Issue by wyu** [PathwayAndDataAnalysis/causalpath-webserver#16]
Hi, I was able to set up the webserver on my Redhat 6 machine. However, I'm getting repeated errors of the same message:

exec error: Error: ENOENT: no such file or directory, open './jar/parameter-info.json'

On the browser, the parameter form is missing the fields as shown in the attachment. Is it possible that the missing "json" file is needed for the parameter definition?

Thanks!
Wen

<img width="1158" alt="Screen Shot 2021-09-05 at 4 36 15 PM" src="https://user-images.githubusercontent.com/760649/132140800-72f207d4-8f54-42d6-84de-dfeff78db0a5.png">

**Comment by ozgunbabur** [comment]
Yes, please follow those steps:

1. Use causalpath.jar to generate the 'parameter-info.json' file by
`java -jar causalpath.jar params-in-json`

2. Put the 'parameter-info.json' file under the 'jar' folder of the webserver.

**Comment by wyu** [comment]
Thanks! Problem solved.

We're still not quite sure if the server is handling the analysis properly. Will come back with a better question once we're done with more testing. This is a wonderful tool that will be vary valuable for us!

Wen

**Comment by ozgunbabur** [comment]
Thanks for investing on CausalPath! We are very interested in your experience. Did you need to solve any difficulty while deploying the webserver to your system? We can use those to update the guidelines on the GitHub page.
